### ISSUE TITLE
installation is confusing

### ISSUE THREAD

**Issue by TopLad75** [Xferno2/Hearts-Of-Iron-IV-Launcher#1]
i can't understand how to install

**Comment by Xferno2** [comment]
Hello,
You have 2 options for installing. You can either [download](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/releases/tag/0.2) the application from here or compile it yourself. Either way, all you have to do is to copy everything from the archive, or the Debug folder if you compiled it yourself, in the root folder of HOI4. The root folder of HOI4 is where you installed it.
For steam it's easy:
1. Select HOI4 from steam right click and go to properties;
![image](https://user-images.githubusercontent.com/25592644/105610927-03443000-5dbb-11eb-85a0-e248c9f2d712.png)
2. Go to local files and press browse;
![image](https://user-images.githubusercontent.com/25592644/105610932-16570000-5dbb-11eb-902e-87e25c194a7d.png)
3. The folder that opens is the root folder so copy everything there;
4. After that you just have to run HOI4 from steam once to generate mod files for subscribed content and that's all.

If you don't have any subscribed content and you download your mods from other sources than steam you can skip 4th step.

**Comment by TopLad75** [comment]
so i downloaded the zip, then unzipped it in my local files, nothing changed. i even took the files out of the folder and had those in my root folder but i still only get the normal launcher no matter how many times i open hoi4

**Comment by TopLad75** [comment]
do i need to use the rar? i'll use the rar

**Comment by Xferno2** [comment]
Do not open the shortcut on desktop of the game or hoi4.exe. Also do not start the game from steam because it won't work, this is a completely different exe. Even tho you won't start your game from steam, leave steam open because once the launcher closes and the game starts you will be playing on steam hoi4.
![image](https://user-images.githubusercontent.com/25592644/106487296-2eb1d380-64bb-11eb-9a0f-0c49e97c4ea8.png)
In the folder you will have the **Hoi4 Launcher.exe** open that to get the launcher. Make a shortcut of that if you want to play with this launcher.
