### ISSUE TITLE
Use gameDataPath setting in launcher-settings.json

### ISSUE THREAD

**Issue by LGhoull** [Xferno2/Hearts-Of-Iron-IV-Launcher#16]
Hey, idk if this project is maintained, but anyway:

I have configured the "gameDataPath" in the launcher-settings.json file to a custom path. When i try to open your launcher, it still searches for the dlc_load.json in the default gameDataPath. Can you fix this?

**Comment by Xferno2** [comment]
I still fix bugs but it's no longer maintained because I'm working on a overhaul of this project.

[Release.zip](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/files/11680843/Release.zip)

Can you try this version? Because I don't have the environment setup to be able to test it. If everything works okay I will update the repository.

**Comment by LGhoull** [comment]
Works.

**Comment by Xferno2** [comment]
Thanks for testing!
