### ISSUE TITLE
No Step Back Launcher Update?

### ISSUE THREAD

**Issue by kev-hidalgo** [Xferno2/Hearts-Of-Iron-IV-Launcher#8]
When I run the launcher the options for no step back and the katyusha music dlc are not there so I was wondering if you were going to update the launcher to include those on the dlc menu.

**Comment by Xferno2** [comment]
Did you allow them to be fully downloaded from steam or from wherever you have the game? Because the list is not hard codded they should all be loaded from your dlc folder in the root folder in hearts of iron. Idk if paradox changed anything to dlcs with the new update. Try run the paradox official launcher first, just in case and tell me if anything changes

**Comment by kev-hidalgo** [comment]
I have it downloaded on Steam and I ran the launcher again and it's still not showing up on the alt launcher.

**Comment by Xferno2** [comment]
I will check soon what's happening there

**Comment by Xferno2** [comment]
I think I fixed it, please check [here](https://github.com/Xferno2/Hearts-Of-Iron-IV-Launcher/releases/tag/v0.3.2.1-alpha), if it works let me know. Also from what I read the Katyusha music is included in No step back, it won't show as a separate dlc. So start the game with No step back and see if you have it

**Comment by kev-hidalgo** [comment]
Yeah it works now thanks for fixing it I appreciate it.
